trigger:
- main

pool:
  name: 'PortafolioAG'

steps:
- task: AzureCLI@2
  displayName: 'Eliminar Azure Blob Storage'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage account delete --name appiumtestreport --resource-group GR-QA --yes